### ISSUE TITLE
Popover freeze after clicking on a button in IOS

### ISSUE THREAD

**Issue by mohdzaid2612** [SteffeyDev/react-native-popover-view#107]
I have 3 buttons inside the popover, and one of the buttons is responsible for showing the model.
 On clicking that button Model is not opening and also freeze the popover.
and also onCloseComplete is not working 
 
 IOS version : 12.0.0 >
Library version : 4.0.1 

Here is my code:
![image](https://user-images.githubusercontent.com/41935754/120169350-7b18e000-c21d-11eb-8266-c0ea582e7ef8.png)

**Comment by SteffeyDev** [comment]
Because the Popover component uses a modal by default, you can't show another modal on top of it (a React Native limitation).  To help with this, I created the `js-modal` mode prop which uses a custom implementation instead of the RN modal, and would allow for a modal to show above the Popover.  However, in `js-modal` mode, placement is a little trickier, so you may have to move the Popover higher up in the view hierarchy to keep the placement working.  See the [section in the README](https://github.com/SteffeyDev/react-native-popover-view#mode) for more info, and let me know if you have additional questions.

**Comment by SteffeyDev** [comment]
Feel free to re-open if you have additional related ssues or feel that my answer does not solve your issue
