### ISSUE TITLE
How can I place a dialog on the popover ?

### ISSUE THREAD

**Issue by sejr1996** [SteffeyDev/react-native-popover-view#138]
I added a popover, but I have a problem, that the dialogs are displayed below the popover.
How can I locate the dialog on the popover?

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-30 at 11 50 57](https://user-images.githubusercontent.com/75812071/171034698-ed8fae59-d23b-4f04-987d-99c566468f20.png)

**Comment by SteffeyDev** [comment]
Try out the 'js-modal' for the `mode` prop, and read the documentation about that. Using 'js-modal' is more difficult because you have to be careful how you position it, but it should fix the problem. I tried to explain how to use it properly on the README, but feel free to continue this thread if you have any problems.
