### ISSUE TITLE
Custom Arrow Color

### ISSUE THREAD

**Issue by craftzdog** [SteffeyDev/react-native-popover-view#3]
Thanks for the great work.

It'd be great if it could change the arrow color of the popover.
What do you think about accepting `style` prop?

**Comment by SteffeyDev** [comment]
What other style elements besides changing the color would you want?  The arrow size has to be it's own prop because it is used to calculate the position of the Popover.  I could easily add an `arrowColor` prop, I feel like adding a `style` prop would lead to a lot of "Why doesn't setting `width`, `height`, `elevation`, `shadowColor`, etc work?" questions.  However, I would consider it if there enough style elements that one would potentially want to change.

**Comment by craftzdog** [comment]
My idea is based on [NativeBase](https://nativebase.io/) components. For example, `Header` accepts `style` prop which lets you change background color, margins, paddings, etc.
`style` prop would work like that for the popover.
If you specify `background: red`, the entire popover color including arrow will be red.
`width` and `height` styles change the size of the popover.

Having props like `arrowColor` would be OK. It's simple.
I have a project that supports UI themes and a dark theme didn't match the popover's default style. So I wanted to change the arrow color.

Thanks for your consideration!

**Comment by SteffeyDev** [comment]
Ok, check out new version 0.7.0, now supports `popoverStyle` and `arrowStyle`.  If you pass a `backgroundColor` to `popoverStyle`, it will also change the background color of the arrow unless you override it with `arrowColor`.  You can also check out `react-native-popover-view-test-app` on Expo & GitHub to see a new button that demos a "Dark Theme".

**Comment by naitik-erpbuddies** [comment]
Is this not available in the current version? @SteffeyDev

**Comment by SteffeyDev** [comment]
I believe the custom background color will still apply to the arrow, but it does appear like the latest version does not support customizing the arrow color to be different then the popover background color. You may have to fork and add yourself, as I'm no longer actively maintaining this project
