### ISSUE TITLE
Component containing the Popover is not clickable

### ISSUE THREAD

**Issue by segalr3** [SteffeyDev/react-native-popover-view#30]
See example here: https://snack.expo.io/Hy8bKJDJ4
the popover itself is clickable but its container component will stop responding to clicks.

**Device/Setup Info:**
 - Device: any
 - OS: iOS
 - `react-native` version: 0.57.4, expo
- `react-native-popover-view` version: 1.014

**Comment by SteffeyDev** [comment]
I am unable to run the snack, tried on various devices and consistently fails to launch.  Can you describe more detail about what the issue is and more importantly what you expect it to do?

**Comment by SteffeyDev** [comment]
I apologize for the delayed response, just catching up from the holiday break still

**Comment by SteffeyDev** [comment]
Ok, I got it to work now.  This is actually by design, a popover is just a modal contained to a smaller area so all taps are captured.  You can use `onClose` prop to catch taps on the background.  The `showBackground` prop just controls the background visibility, but it is always there.  The `showInModal` prop only controls whether it is shown in a RN `Modal` component or shown in a JS-only view that takes over the screen in a similar manner (that may be misleading, sorry).  Hopefully that helps with your issue.

As another note, it is best practice to keep the `Popover` component outside of the `Touchable`, as a sibling.

If you would like the ability to keep the popover open while having taps go through to the background, please open a new issue as a feature request, and we can discuss the feasibility of that there.

**Comment by SteffeyDev** [comment]
@segalr3 I just released version 2.0.0 that includes a `tooltip` mode to do exactly what you were looking to do!  Thanks for the idea, I hope you find it useful.  Let me know if you have any issues with it.

**Comment by segalr3** [comment]
@SteffeyDev cool! I will look into it as soon as I can!
