### ISSUE TITLE
Bug in calculating size

### ISSUE THREAD

**Issue by kev71187** [SteffeyDev/react-native-popover-view#55]
**Describe the bug**
There are two bugs that cause the initial calculation of the popover to frequently be incorrect and cause incorrect animate slide in effects.

- https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Popover.js#L912
There is a race condition here with https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Popover.js#L902
Line 902 gets triggered twice. If line 912 executes before the second event the bug happens. If the it executes after the second event the code acts correctly. I was able to fix this race condition by adding a setTimeout to line 912 with a delay of 1 to get it put the animation at the end of the call stack.

- https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Popover.js#L13
That is calculated on import and therefore is not recalculated with the device rotates. This should be moved to a dynamically calculated value.

**Device/Setup Info:**
 - Device: iPad Air Simulator
 - OS: iOS 13.3
 - `react-native` version:  0.61
- `react-native-popover-view` version: 2.04

**Screenshots**
![bug-popover-gif](https://user-images.githubusercontent.com/2372855/73552060-8b486180-4415-11ea-92d4-a80c8d6be49e.gif)

**Comment by SteffeyDev** [comment]
Thanks for debugging this! I’ve seen this behavior before but didn’t have time to figure it out. I’ll check out your pull request this weekend, test it out, and hopefully release a new version.

**Comment by SteffeyDev** [comment]
Ok, change merged and published as 2.0.6

**Comment by AndrewMorsillo** [comment]
@SteffeyDev Maybe something went wrong with the publish? I just updated to 2.0.6 and this commit is not in there.

**Comment by SteffeyDev** [comment]
Nope, if you look closely that commit was just updating formatting, same code

**Comment by AndrewMorsillo** [comment]
If I'm reading it correctly (and correct me if I'm not) ```const layout = evt.nativeEvent.layout``` got removed which is actually a significant change. Removing that line delays the access of the` layout` prop until it is run inside the  `setTimeout`. At least on my emulator accessing `evt.nativeEvent.layout` inside the timeout crashes because `nativeEvent` is null. It works if I add the line back in there to bind `eat.nativeEvent.layout` to the const before the timeout.

**Comment by SteffeyDev** [comment]
Interesting, I don't know too in depth how it works under the hood but I assumed them to be equivalent.  Certainly assigning the object reference to a new variable shouldn't effect anything, I wonder why that changes? Let me test and get back to you

**Comment by AndrewMorsillo** [comment]
It's a subtle thing but tools like typescript can help warn you about it. For example:

```
let foo = { bar: "asdf" }
setTimeout(() => { console.log(foo.bar.length) }, 500)
foo.bar = null
```

and 500ms later `cannot access property length of null`

but if you do this

```
let foo = { bar: "asdf" }
const barValue = foo.bar
setTimeout(() => { console.log(barValue.length) }, 500)
foo.bar = null
```

Then 500ms later your program prints "4"

When you access a mutable object in a callback or setTimeout nothing guarantees that the object you're accessing won't get changed before your callback runs.

**Comment by SteffeyDev** [comment]
That makes sense because `foo.bar` is a value, where in our example `layout` is an object, so in theory it only copies the reference.  If you truly wanted to protect against null you should do `const layout = { ...evt.nativeEvent.layout }` to make a copy of the object instead of just storing its reference in a different variable.

**Comment by SteffeyDev** [comment]
Ok 2.0.7 has that change.

**Comment by AndrewMorsillo** [comment]
Thanks!

You're right about the object vs value thing but even if you use the object spread operator it doesn't totally guard against accessing a null reference because IIRC object spread is not recursive. If you accessed any nested objects ex `layout.foo.bar` those could be null as well. In this case however it seems that the layout object is safe and just the nativeEvent reference is getting nullified.
