### ISSUE TITLE
mode={'tooltip'} not opens popover

### ISSUE THREAD

**Issue by varshan09** [SteffeyDev/react-native-popover-view#59]
I want to open pop over without dim effect, I have tried to use mode = {'tooltip} but after using mode popover is not opening. It's working fine with 'rn-modal' .

`<Popover
                isVisible={this.state.modalVisible}
                mode={"tooltip"}
                popoverStyle={{ backgroundColor: 'transparent' }}
                onRequestClose={() =>
                    this.setState({
                        modalVisible: false,
                        selectedItem: ""
                    })
                }
            >`

**Comment by SteffeyDev** [comment]
You can set the `backgroundStyle` prop if you just want to make the background transparent (something like `backgrounsStyle={{ backgroundColor: 'transparent' }}`), but that will leave the overlay in place so that when you tap outside the popover it will dismiss.  If you would like to not show the overlay period, so that tapping outside goes through to other components, then tooltip mode is correct.  If there is an issue with tooltip mode, please provide more specific details.
